// TODO rewrite all the files in the commit that this comment was written in

/// Constants needed by the `cos_sin_*` implementations. The values actually
/// used are generated by `gen_constants` in the testcrate of the repo
/// containing this crate.
///
/// The coefficient tables store the _magnitudes_ of the alternating series
/// coefficients of
///
/// cos((pi/4)*t) = a_0 - a_1*t^2 + a_2*t^4 - ...
/// sin((pi/4)*t) = t*(b_0 - b_1*t^2 + b_2*t^4 - ...)
///
/// for `t` in the full fracint range, corresponding to an eighth of a turn in
/// each direction. This interval is used because it is the largest one for
/// which all of the coefficients (Taylor or minimax) have magnitudes less
/// than 1, so that plain Horner evaluation never overflows.
///
/// `F` is the fracint type itself and `D` is the type the accurate Taylor
/// tables are stored at, which is the double width type when it exists (the
/// accurate variants evaluate their polynomials at double width so that
/// almost all of the truncation error is rounded off at the end).
pub struct TrigConsts<F: 'static, D: 'static> {
    /// sqrt(1/2), i.e. cos(pi/4)
    pub sqrt_half: F,
    /// 1/pi
    pub inv_pi: F,
    /// Taylor coefficient magnitudes for cosine
    pub cos_coeffs: &'static [D],
    /// Taylor coefficient magnitudes for sine
    pub sin_coeffs: &'static [D],
    /// minimax coefficient magnitudes for cosine used by the `_fast` variants
    pub cos_coeffs_fast: &'static [F],
    /// minimax coefficient magnitudes for sine used by the `_fast` variants
    pub sin_coeffs_fast: &'static [F],
}

/// Generates the public `cos_sin_*` functions. Requires inherent
/// `cos_sin_eighth_taylor` and `cos_sin_eighth_fast` functions that compute
/// `(cos((pi/4)*t), sin((pi/4)*t))` for any `t != MIN`.
#[macro_export]
macro_rules! impl_cos_sin_common {
    ($ty:ident, $iX:ident, $uX:ident, $c:expr) => {
        /// Computes `(cos(pi * self), sin(pi * self))`, i.e. `self` is the
        /// angle in half turns, so that the entire wrapping range of the type
        /// maps exactly onto the full circle.
        ///
        /// This is the parameterization that uses the bits of a fracint most
        /// efficiently: `fiN::MIN` acts as exactly -1.0 half turns, wrapping
        /// arithmetic on `self` corresponds exactly to modular angle
        /// arithmetic, and the quadrant reduction here is lossless. Values
        /// with magnitude 1.0 (and the outputs at exact quadrant boundaries)
        /// are handled specially, e.g. `fiN::MIN` maps to `(-fiN::ONE,
        /// fiN::ZERO)` and `(fiN::MIN / -2)` maps to `(fiN::ZERO, fiN::ONE)`.
        ///
        /// Measured maximum error: 1 ULP for the types with a double width
        /// type to evaluate in (fi8 through fi64, which are correctly
        /// rounded in almost all cases), and a few ULPs for fi128.
        pub fn cos_sin_pi(self) -> (Self, Self) {
            // offset by an eighth turn so that the two highest bits of `o`
            // are the quadrant index, with quadrant boundaries centered on
            // the axes
            let o = (self.0 as $uX).wrapping_add(1 << (Self::BITS - 3));
            let q = o >> (Self::BITS - 2);
            // in [-0.25, 0.25), the offset in half turns from the nearest
            // axis angle
            let r = self.0.wrapping_sub((q << (Self::BITS - 2)) as $iX);
            // in [-1.0, 1.0), the same offset in eighth turns
            let t = Self(((r as $uX) << 2) as $iX);
            let (c, s) = if t == Self::MIN {
                // `t` is exactly -1.0 eighth turns, which the polynomial
                // evaluation cannot handle because `t*t` overflows
                ($c.sqrt_half, $c.sqrt_half.wrapping_neg())
            } else {
                t.cos_sin_eighth_taylor()
            };
            // rotate by the quadrant index. the outputs of the base function
            // never include `MIN`, so `wrapping_neg` cannot overflow.
            match q {
                0 => (c, s),
                1 => (s.wrapping_neg(), c),
                2 => (c.wrapping_neg(), s.wrapping_neg()),
                _ => (s, c.wrapping_neg()),
            }
        }

        /// Computes `(cos(tau * self), sin(tau * self))`, i.e. `self` is the
        /// angle in full turns.
        ///
        /// This is exactly equivalent to `(self << 1).cos_sin_pi()`: the
        /// most significant bit of `self` is redundant (`x` and `x + 1.0`
        /// turns are the same angle), so this parameterization has half the
        /// angular resolution of [cos_sin_pi](Self::cos_sin_pi).
        pub fn cos_sin_tau(self) -> (Self, Self) {
            Self(((self.0 as $uX) << 1) as $iX).cos_sin_pi()
        }

        /// The same as [cos_sin_pi](Self::cos_sin_pi) except with a faster,
        /// less accurate polynomial.
        ///
        /// Measured maximum error: 2 to 3 ULPs for fi8 and fi16 (which use a
        /// polynomial with absolute error around 1.0e-5), and an absolute
        /// error around 2.8e-8 for fi32 and larger (about 61 ULPs of fi32).
        /// The eighth turn boundary values are still exact.
        pub fn cos_sin_pi_fast(self) -> (Self, Self) {
            let o = (self.0 as $uX).wrapping_add(1 << (Self::BITS - 3));
            let q = o >> (Self::BITS - 2);
            let r = self.0.wrapping_sub((q << (Self::BITS - 2)) as $iX);
            let t = Self(((r as $uX) << 2) as $iX);
            let (c, s) = if t == Self::MIN {
                ($c.sqrt_half, $c.sqrt_half.wrapping_neg())
            } else {
                t.cos_sin_eighth_fast()
            };
            match q {
                0 => (c, s),
                1 => (s.wrapping_neg(), c),
                2 => (c.wrapping_neg(), s.wrapping_neg()),
                _ => (s, c.wrapping_neg()),
            }
        }

        /// The same as [cos_sin_tau](Self::cos_sin_tau) except with a faster,
        /// less accurate polynomial.
        pub fn cos_sin_tau_fast(self) -> (Self, Self) {
            Self(((self.0 as $uX) << 1) as $iX).cos_sin_pi_fast()
        }

        /// The same as [cos_sin_rad](Self::cos_sin_rad) except with a faster,
        /// less accurate polynomial.
        pub fn cos_sin_rad_fast(self) -> (Self, Self) {
            self.wrapping_mul($c.inv_pi).cos_sin_pi_fast()
        }
    };
}

/// Adds `cos_sin_*` functions to a signed fracint that has a double width
/// type. `$c` should be a `TrigConsts<$ty, $tyD>`.
#[macro_export]
macro_rules! impl_cos_sin {
    ($ty:ident, $tyD:ident, $iX:ident, $uX:ident, $c:expr) => {
        impl $ty {
            $crate::impl_cos_sin_common!($ty, $iX, $uX, $c);

            /// Rounds a double width value to the nearest `Self`
            fn round_from_double(x: $tyD) -> $ty {
                // adding half of a `$ty::ULP` and then flooring rounds to
                // nearest, and the saturation handles values near 1.0
                x.saturating_add($tyD::ULP << ($ty::BITS - 1)).truncate()
            }

            /// Computes `(cos((pi/4) * self), sin((pi/4) * self))`, i.e.
            /// `self` is the angle in eighth turns. `self` must not be `MIN`.
            ///
            /// The polynomials are evaluated at double width with an exact
            /// widened `self * self`, so the Horner truncation errors are
            /// all far below the final rounding and the total error is
            /// around 1 ULP.
            fn cos_sin_eighth_taylor(self) -> ($ty, $ty) {
                debug_assert!(self != $ty::MIN);
                let u = self.saturating_widening_mul(self);
                let cc = $c.cos_coeffs;
                let mut acc = cc[cc.len() - 1];
                for i in (0..(cc.len() - 1)).rev() {
                    acc = cc[i].wrapping_sub(u.wrapping_mul(acc));
                }
                let cos = $ty::round_from_double(acc);
                let sc = $c.sin_coeffs;
                let mut acc = sc[sc.len() - 1];
                for i in (0..(sc.len() - 1)).rev() {
                    acc = sc[i].wrapping_sub(u.wrapping_mul(acc));
                }
                let sin = $ty::round_from_double(self.widen().wrapping_mul(acc));
                (cos, sin)
            }

            /// The single width minimax version of `cos_sin_eighth_taylor`
            fn cos_sin_eighth_fast(self) -> ($ty, $ty) {
                debug_assert!(self != $ty::MIN);
                let u = self.wrapping_mul(self);
                let cc = $c.cos_coeffs_fast;
                let mut acc = cc[cc.len() - 1];
                for i in (0..(cc.len() - 1)).rev() {
                    acc = cc[i].wrapping_sub(u.wrapping_mul(acc));
                }
                let cos = acc;
                let sc = $c.sin_coeffs_fast;
                let mut acc = sc[sc.len() - 1];
                for i in (0..(sc.len() - 1)).rev() {
                    acc = sc[i].wrapping_sub(u.wrapping_mul(acc));
                }
                let sin = self.wrapping_mul(acc);
                (cos, sin)
            }

            /// Computes `(cos(self), sin(self))`, i.e. `self` is the angle
            /// in radians, which restricts the angle to the unit range of
            /// the type.
            ///
            /// Note that unlike the half turn and full turn
            /// parameterizations, converting to radians involves an
            /// inexact multiplication by 1/pi, which adds around 1 ULP of
            /// angular error on top of the error of
            /// [cos_sin_pi](Self::cos_sin_pi), for a measured maximum error
            /// of around 3 ULPs. Prefer the turn based parameterizations
            /// when possible.
            pub fn cos_sin_rad(self) -> (Self, Self) {
                // the product with the 1/pi constant is exact at double
                // width, round it to the nearest single width half turn
                // angle
                let h = Self::round_from_double(self.saturating_widening_mul($c.inv_pi));
                h.cos_sin_pi()
            }
        }
    };
}

/// Adds `cos_sin_*` functions to a signed fracint with no double width type,
/// using single width evaluation. `$c` should be a `TrigConsts<$ty, $ty>`.
#[macro_export]
macro_rules! impl_cos_sin_single {
    ($ty:ident, $iX:ident, $uX:ident, $c:expr) => {
        impl $ty {
            $crate::impl_cos_sin_common!($ty, $iX, $uX, $c);

            /// Computes `(cos((pi/4) * self), sin((pi/4) * self))`, i.e.
            /// `self` is the angle in eighth turns. `self` must not be `MIN`.
            ///
            /// There is no double width type to evaluate in, so the Horner
            /// truncation errors accumulate to several ULPs.
            fn cos_sin_eighth_taylor(self) -> ($ty, $ty) {
                debug_assert!(self != $ty::MIN);
                let u = self.wrapping_mul(self);
                let cc = $c.cos_coeffs;
                let mut acc = cc[cc.len() - 1];
                for i in (0..(cc.len() - 1)).rev() {
                    acc = cc[i].wrapping_sub(u.wrapping_mul(acc));
                }
                let cos = acc;
                let sc = $c.sin_coeffs;
                let mut acc = sc[sc.len() - 1];
                for i in (0..(sc.len() - 1)).rev() {
                    acc = sc[i].wrapping_sub(u.wrapping_mul(acc));
                }
                let sin = self.wrapping_mul(acc);
                (cos, sin)
            }

            /// The truncated minimax version of `cos_sin_eighth_taylor`
            fn cos_sin_eighth_fast(self) -> ($ty, $ty) {
                debug_assert!(self != $ty::MIN);
                let u = self.wrapping_mul(self);
                let cc = $c.cos_coeffs_fast;
                let mut acc = cc[cc.len() - 1];
                for i in (0..(cc.len() - 1)).rev() {
                    acc = cc[i].wrapping_sub(u.wrapping_mul(acc));
                }
                let cos = acc;
                let sc = $c.sin_coeffs_fast;
                let mut acc = sc[sc.len() - 1];
                for i in (0..(sc.len() - 1)).rev() {
                    acc = sc[i].wrapping_sub(u.wrapping_mul(acc));
                }
                let sin = self.wrapping_mul(acc);
                (cos, sin)
            }

            /// Computes `(cos(self), sin(self))`, i.e. `self` is the angle
            /// in radians, which restricts the angle to the unit range of
            /// the type.
            ///
            /// Note that unlike the half turn and full turn
            /// parameterizations, converting to radians involves an
            /// inexact multiplication by 1/pi, which adds around 2 ULP of
            /// angular error on top of the error of
            /// [cos_sin_pi](Self::cos_sin_pi), for a measured maximum error
            /// of around 8 ULPs. Prefer the turn based parameterizations
            /// when possible.
            pub fn cos_sin_rad(self) -> (Self, Self) {
                self.wrapping_mul($c.inv_pi).cos_sin_pi()
            }
        }
    };
}
