[package]
name = "fracints"
version = "0.2.1"
edition = "2024"
authors = ["Aaron Kutch <aaronkutch@att.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/AaronKutch/fracints"
documentation = "https://docs.rs/fracints"
description = "Special case fractional-only fixed point numbers"
keywords = ["numerics", "math", "no_std"]
categories = ["data-structures", "mathematics", "algorithms", "no-std"]

[dependencies]
awint = { workspace = true }
# for important doc dependency
awint_core = { workspace = true }
fracints_internals = { workspace = true }
fracints_macros = { workspace = true }
rand_core = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }

[features]
default = ["std"]
std = []
rand_support = ["rand_core", "fracints_internals/rand_support"]
serde_support = ["serde"]
